### ISSUE TITLE
500 internal server error with 3.1

### ISSUE THREAD

**Issue by Joukahainen123** [matamorphosis/Scrummage#18]
Hi

I have a fresh install of 3.1 version (Ubuntu 20.4.1 LTS). When I try to login, I will get erro 500 and the following error can be seen in the logs:

WARNING:Scrummage:Successful login from admin.
INFO:werkzeug:192.168.1.105 - - [20/Dec/2020 11:40:34] "POST /login HTTP/1.1" 302 -
ERROR:Scrummage:Date() got an unexpected keyword argument 'Additional_Last_Days'
ERROR:Scrummage:Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:192.168.1.105 - - [20/Dec/2020 11:40:34] "GET /dashboard HTTP/1.1" 500 -

**Comment by matamorphosis** [comment]
Hi thanks for raising this, the latest update to the General.py library hadn't gone through, please pull the latest commit and try again.

**Comment by Joukahainen123** [comment]
Now working. Thanks.
