### ISSUE TITLE
oauth2client problem with Google search

### ISSUE THREAD

**Issue by Joukahainen123** [matamorphosis/Scrummage#8]
Hi

I have a fresh install of Scrummage in Ubuntu 20. 04. Trying,to run my first Google search, the Google settings should be right (copied from working Scumblr installation). For some reason I get no results whatsoever. Logs have the following errors:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 40, in <module>
    raise ImportError(
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
WARNING:root:2020-07-05 08:23:38 - Google_Search - name: customsearch  version: 1.0
INFO:root:2020-07-05 08:23:38 Connectors Library - Loading Scrummage's Main Database configuration data.

**Comment by matamorphosis** [comment]
Hey again Joukahainen123,

Thanks for calling this out, this issue is more of a warning than an error. I disabled the in-built caching feature which has resolved it. Please pull the latest changes and try again.

Cheers,

matamorphosis
